# Generated by Django 2.2.1 on 2019-06-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
    ]
