# Generated by Django 2.2.1 on 2019-05-31 21:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financetype', models.CharField(max_length=100)),
                ('credittype', models.CharField(max_length=100)),
                ('propvalue', models.CharField(max_length=100)),
                ('firstmortgagebalance', models.CharField(max_length=100)),
                ('firstmortgagerate', models.CharField(max_length=100)),
                ('secondmortgagebalance', models.CharField(max_length=100)),
                ('secondmortgagerate', models.CharField(max_length=100)),
                ('borrowamount', models.CharField(max_length=100)),
                ('incometype', models.CharField(max_length=100)),
                ('incomerange', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('postalcode', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=100)),
                ('contact_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
